apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-ldp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-dn
  template:
    metadata:
      labels:
        app: flask-dn
    spec:
      containers:
      - name: flask-container-ldp
        image: axos15/flask-actions-project
        ports:
        - containerPort: 7897
          name: flaskwebsvc-ldp