apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: flask-deployment-ldp
  labels:
    app.kubernetes.io/name: flask-ldp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-ldp
  template:
    metadata:
      labels:
        app: flask-ldp
    spec:
      containers:
      - name: flask-container-ldp
        image: axos15/flask-actions-project
        ports:
        - containerPort: 5000
          name: flaskweb-ldp