apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-ldp-new
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskldp  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: flaskldp 
    spec:
      containers:
      - name: flask-container-ldp
        image: axos15/flask-actions-project
        ports:
        - containerPort: 5000
