apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-ldp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskldp  
  template:
    metadata:
      labels:
        app: flaskldp  
    spec:
      containers:
      - name: flask-app
        image: your-flask-image
        ports:
        - containerPort: 5000
