apiVersion: v1
kind: Service
metadata:
  name: flask-service-ldp
spec:
  selector:
    app: flaskl-dp
  ports:
  - name: flask-service-port
    protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer