apiVersion: v1
kind: Service
metadata:
  name: flask-service-ldp
spec:
  selector:
    app.kubernetes.io/name: flask-ldp
  type: LoadBalancer
  ports:
  - name: flask-service-port
    protocol: TCP
    port: 80
    targetPort: 5000